set nu cin sts=4 ts=4 sw=4
map <F5> :call CR()<CR>
func CR()
	exec "w"
	exec "!clear && g++ % -std=c++14 -W -o a && ./a < in"
endfunc
map <F9> :call CRr()<CR>
func CRr()
	exec "w"
	exec "!clear && g++ % -std=c++14 -W -o a && ./a"
endfunc
imap {<CR> {<CR>}<C-O>O<left><right>